
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftMENOSMASleftMULTIDIVrightUNARIOCHAR DECIMAL DIV ENTERO MAS MENOS MULTI PARA PARC STRING\n    inicio : instruccion\n    \n    instruccion : expression\n    \n    expression :  expression MAS expression \n            |   expression MENOS expression\n            |   expression DIV expression\n            |   expression MULTI expression \n    \n    expression : PARA expression PARC\n    \n    expression : ENTERO\n        | DECIMAL\n    \n    expression : MAS expression\n           | MENOS expression %prec UNARIO\n    '
    
_lr_action_items = {'PARA':([0,4,5,6,9,10,11,12,],[6,6,6,6,6,6,6,6,]),'ENTERO':([0,4,5,6,9,10,11,12,],[7,7,7,7,7,7,7,7,]),'DECIMAL':([0,4,5,6,9,10,11,12,],[8,8,8,8,8,8,8,8,]),'MAS':([0,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,],[4,9,4,4,4,-8,-9,4,4,4,4,-10,-11,9,-3,-4,-5,-6,-7,]),'MENOS':([0,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,],[5,10,5,5,5,-8,-9,5,5,5,5,-10,-11,10,-3,-4,-5,-6,-7,]),'$end':([1,2,3,7,8,13,14,16,17,18,19,20,],[0,-1,-2,-8,-9,-10,-11,-3,-4,-5,-6,-7,]),'DIV':([3,7,8,13,14,15,16,17,18,19,20,],[11,-8,-9,11,-11,11,11,11,-5,-6,-7,]),'MULTI':([3,7,8,13,14,15,16,17,18,19,20,],[12,-8,-9,12,-11,12,12,12,-5,-6,-7,]),'PARC':([7,8,13,14,15,16,17,18,19,20,],[-8,-9,-10,-11,20,-3,-4,-5,-6,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'inicio':([0,],[1,]),'instruccion':([0,],[2,]),'expression':([0,4,5,6,9,10,11,12,],[3,13,14,15,16,17,18,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> inicio","S'",1,None,None,None),
  ('inicio -> instruccion','inicio',1,'p_inicio','parser.py',22),
  ('instruccion -> expression','instruccion',1,'p_instruccion','parser.py',28),
  ('expression -> expression MAS expression','expression',3,'p_expression','parser.py',34),
  ('expression -> expression MENOS expression','expression',3,'p_expression','parser.py',35),
  ('expression -> expression DIV expression','expression',3,'p_expression','parser.py',36),
  ('expression -> expression MULTI expression','expression',3,'p_expression','parser.py',37),
  ('expression -> PARA expression PARC','expression',3,'p_expression_par','parser.py',56),
  ('expression -> ENTERO','expression',1,'p_factor_number','parser.py',64),
  ('expression -> DECIMAL','expression',1,'p_factor_number','parser.py',65),
  ('expression -> MAS expression','expression',2,'p_factor_unario','parser.py',72),
  ('expression -> MENOS expression','expression',2,'p_factor_unario','parser.py',73),
]
